### PR TITLE
Clear The Screen

### PR DESCRIPTION
**Pull request by aoowweenn**
Since we choose Mailbox present mode,
the order of images and framebuffers is not guaranteed to be the same as command buffers.
command buffer index should follow the corresponding `flight_fence`.

Fixed Validation Error:  #6 

> Calling vkBeginCommandBuffer() on active command buffer before it has completed.

### CODE REVIEW

**Comment by Lokathor** [comment]
I merged a small fix to master but it should be simple for you to update, since I don't believe any affected files were ones you're updating here.

**Comment by Lokathor** [comment]
@aoowweenn So I don't fully understand this change and I'll let termhn make the call, but in the lesson from the vulkan-tutorial.com that this was based on ([here](https://vulkan-tutorial.com/Drawing_a_triangle/Drawing/Rendering_and_presentation)) they explicitly say to pick the command buffer based on the image index acquired. Can you explain why they're wrong a bit more? They also suggest [using mailbox](https://vulkan-tutorial.com/Drawing_a_triangle/Presentation/Swap_chain) in their tutorial so it's not like they account. The vulkan error you're referring to doesn't get reported with the latest version of the demo on my machine.

**Comment by Lokathor** [comment]
I finally had a chance to examine this closely, and you're right.

Which of your two solutions to use is a tough one.
* On the one hand, the style that's currently in your PR keeps all of the ring-buffer resources lined up with each other.
* On the other hand, allowing the image selected to jump around regardless of your other elements is kinda the whole point of mailbox mode.

Let's go with the alternate code from your comment there. Can you update your branch and also edit it to use that style solution? (Sorry about forcing another update, `termhn` wrote up an unexpected demo for instanced drawing.)

**Comment by aoowweenn** [comment]
Fine, I have finished updating the solution, please check then.

**Pull request merged**
