### PR TITLE
`HalState` generalization

### PR DESCRIPTION
**Pull request by AlterionX**
Added a subsection to chapter 6, which is the first mention of generalizing `HalState`.

Added an example for the generalization, called `generalization.rs`.

### CODE REVIEW

**Comment by Lokathor** [comment]
CI seems good, which is a great sign. I'll have to check through this carefully when I have a moment to sit down and go over it.

**Comment by Lokathor** [comment]
This is very good stuff. Sorry it's taken me so long to get back to the PR. I'll have bors merge this once the basic CI passes.

**Comment by AlterionX** [comment]
That's fine. Also, why did bors fail :cry:. Anything I can do to fix that? I can't see the reasons why it failed.

**Comment by Lokathor** [comment]
yeah, sometimes bors is a bit of a flake

bors r+

**Pull request merged**
